### ISSUE TITLE
Job Opportunity - Interested?

### ISSUE THREAD

**Issue by beyourseff** [nathane/contact-me#2]
Hey @nathane, hope this is the right way to contact you! I'm reaching out with a job opportunity you might be interested in.

To briefly intro myself: my name is Yousef and I'm the founder of toffee.com which is a marketplace for trading digital goods. The goal is to help anyone sell a digital product, both via their own storefront as well as on a global marketplace.

My plan is to rewrite Toffee from scratch and use Laravel Blueprint for the initial scaffolding. I came across your profile on the Blueprint repo and saw that you were very familiar with it, which is why I decided to reach out. If you are interested/available, I'd very much like to take you on for the rewrite project (and if you're interested, after that as well) on either part-time or full-time basis, whichever works best for you.

Let me know! Happy to provide more detailed info if this is something you'd be interested in :)

**Comment by beyourseff** [comment]
Hi @nathane re-pinging ICYMT :)

**Comment by ghostwriter** [comment]
Hey @beyourseff,

First, Thank you for this Job Opportunity. Unfortunately, I am currently unavailable for additional work for the time being. I'm however working on v2 of Blueprint and would love to help you by answering any questions and provide feedback via Issues in the Blueprint repo.

Again, Thank you for this opportunity. Sorry, it took me so long to respond.

**Comment by beyourseff** [comment]
Not a worry @nathane I've actually found a great lead developer in the meantime. If we do run into any issues while working on our blueprint, I'll make sure to reach out via the Issues in the Blueprint repo.

PS: If you do become available some time in the future, don't hesitate to reach out :)

**Comment by ghostwriter** [comment]
I'm glad to hear that @beyourseff, and I will. 🙂
